# Generated by Django 2.1.3 on 2018-12-26 09:12

from django.db import migrations, models
import fast_drf.mixins.expose_api_model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
            ],
            bases=(fast_drf.mixins.expose_api_model_mixin.ExposeApiModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('example_app.userprofile',),
        ),
    ]
